/*
Nome: André Moreira Souza    N°USP: 9778985
Prática 2 – SQL - DDL
*/

-- Exercício 1:

-- para remover tabelas existentes
--SELECT 'DROP TABLE ' ||TABLE_NAME|| ' CASCADE CONSTRAINTS;' FROM USER_TABLES;

CREATE TABLE EQUIPE (
	NOME VARCHAR2 (64) NOT NULL,
	NCOMPONENTES NUMBER (6, 0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_EQUIPE PRIMARY KEY (NOME),
	CONSTRAINT CK_EQUIPE_0 CHECK (NCOMPONENTES >= 0)
);

CREATE TABLE SEGURANCA (
	NCADASTRO NUMBER (6, 0) NOT NULL,
	NOME VARCHAR2 (64) NOT NULL,
	FUNCAO VARCHAR2 (64) NOT NULL,
	TURNO VARCHAR2 (16),
	EQUIPE VARCHAR2 (64),
	CONSTRAINT PK_SEGURANCA PRIMARY KEY (NCADASTRO),
	CONSTRAINT FK_SEGURANCA_0 FOREIGN KEY (EQUIPE)
		REFERENCES EQUIPE(NOME)
		ON DELETE SET NULL
);

CREATE TABLE TIME (
	PAIS VARCHAR2 (64) NOT NULL,
	NFIFA NUMBER (6, 0) NOT NULL,
	EQUIPESEG VARCHAR2 (64),
	PROCSEG VARCHAR2 (64),
	BANDEIRA BLOB,
	NGOLS NUMBER (3, 0) DEFAULT 0 NOT NULL,
	TECNICO VARCHAR2 (64),
	GRUPO CHAR(1),
	PONTUACAO NUMBER (2, 0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TIME PRIMARY KEY (PAIS),
	CONSTRAINT UK_TIME_0 UNIQUE (NFIFA),
	CONSTRAINT FK_TIME_0 FOREIGN KEY (EQUIPESEG)
		REFERENCES EQUIPE(NOME)
		ON DELETE SET NULL,
	CONSTRAINT CK_TIME_0 CHECK (PONTUACAO >= 0),
	CONSTRAINT CK_TIME_1 CHECK (GRUPO IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'))
);

CREATE TABLE OCORRENCIATIME (
	TIME VARCHAR2 (64) NOT NULL,
	NOCORRENCIA NUMBER (6, 0) NOT NULL,
	DESCRICAO VARCHAR2 (256) NOT NULL,
	CONSTRAINT PK_OCORRENCIATIME PRIMARY KEY (TIME, NOCORRENCIA),
	CONSTRAINT FK_OCORRENCIATIME_0 FOREIGN KEY (TIME)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE
);

CREATE TABLE HOTEL (
	NOME VARCHAR2 (64) NOT NULL,
	CIDADE VARCHAR2 (64) NOT NULL,
	CONSTRAINT PK_HOTEL PRIMARY KEY (NOME)
);

CREATE TABLE HOSPEDA (
	TIME VARCHAR2 (64) NOT NULL,
	HOTEL VARCHAR2 (64) NOT NULL,
	NDELEGACAO NUMBER (3, 0) NOT NULL,
	CONSTRAINT PK_HOSPEDA PRIMARY KEY (TIME, HOTEL),
	CONSTRAINT FK_HOSPEDA_0 FOREIGN KEY (TIME)
		REFERENCES TIME(PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_HOSPEDA_1 FOREIGN KEY (HOTEL)
		REFERENCES HOTEL(NOME)
		ON DELETE CASCADE,
	CONSTRAINT CK_HOSPEDA_0 CHECK (NDELEGACAO > 0)
);

CREATE TABLE PERIODOHOSP (
	TIME VARCHAR2 (64) NOT NULL,
	HOTEL VARCHAR2 (64) NOT NULL,
	DTAENTRADA DATE NOT NULL,
	DTASAIDA DATE,
	CONSTRAINT PK_PERIODOHOSP PRIMARY KEY (TIME, HOTEL, DTAENTRADA),
	CONSTRAINT FK_PERIODOHOSP_0 FOREIGN KEY (TIME)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_PERIODOHOSP_1 FOREIGN KEY (HOTEL)
		REFERENCES HOTEL (NOME)
		ON DELETE CASCADE,
	CONSTRAINT CK_PERIODOHOSP_0 CHECK (DTASAIDA > DTAENTRADA)
);

CREATE TABLE JOGADOR (
	NFIFA NUMBER (6, 0) NOT NULL,
	NOME VARCHAR2 (64) NOT NULL,
	APELIDO VARCHAR2 (64),
	DTANASC DATE NOT NULL,
	POSICAO VARCHAR2 (16) NOT NULL,
	CAPITAO CHAR(1) DEFAULT 'N' NOT NULL,
	TIME VARCHAR2 (64) NOT NULL,
	CONSTRAINT PK_JOGADOR PRIMARY KEY (NFIFA),
	CONSTRAINT FK_JOGADOR_0 FOREIGN KEY (TIME)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE,
	CONSTRAINT CK_JOGADOR_0 CHECK (CAPITAO IN ('S', 'N'))
);

CREATE TABLE ESTADIO (
	NOME VARCHAR2 (64) NOT NULL,
	CIDADE VARCHAR2 (64) NOT NULL,
	CAPACIDADE NUMBER (6, 0) NOT NULL,
	CONSTRAINT PK_ESTADIO PRIMARY KEY (NOME),
	CONSTRAINT CK_ESTADIO_0 CHECK (CAPACIDADE >= 0)
);

CREATE TABLE DISTA (
	HOTEL VARCHAR2 (64) NOT NULL,
	ESTADIO VARCHAR2 (64) NOT NULL,
	DISTANCIA NUMBER (8, 2) NOT NULL,
	CONSTRAINT PK_DISTA PRIMARY KEY (HOTEL, ESTADIO),
	CONSTRAINT FK_DISTA_0 FOREIGN KEY (HOTEL)
		REFERENCES HOTEL (NOME)
		ON DELETE CASCADE,
	CONSTRAINT FK_DISTA_1 FOREIGN KEY (ESTADIO)
		REFERENCES ESTADIO (NOME)
		ON DELETE CASCADE,
	CONSTRAINT CK_DISTA_0 CHECK (DISTANCIA >= 0)
);

CREATE TABLE TREINA (
	TIME VARCHAR2 (64) NOT NULL,
	ESTADIO VARCHAR2 (64) NOT NULL,
	DTATREINO DATE NOT NULL,
	CONSTRAINT PK_TREINA PRIMARY KEY (TIME, ESTADIO, DTATREINO),
	CONSTRAINT FK_TREINA_0 FOREIGN KEY (TIME)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_TREINA_1 FOREIGN KEY (ESTADIO)
		REFERENCES ESTADIO (NOME)
		ON DELETE CASCADE
);

CREATE TABLE JOGO (
	NUMERO NUMBER (6, 0) NOT NULL,
	FASE VARCHAR2 (16) NOT NULL,
	TIME1 VARCHAR2 (64) NOT NULL,
	TIME2 VARCHAR2 (64) NOT NULL,
	DATAHORA DATE,
	NGOLS1 NUMBER (3, 0) DEFAULT 0 NOT NULL,
	NGOLS2 NUMBER (3, 0) DEFAULT 0 NOT NULL,
	ESTADIO VARCHAR2 (64) NOT NULL,
	ARBITRO VARCHAR2 (64),
	ASSISTENTE1 VARCHAR2 (64),
	ASSISTENTE2 VARCHAR2 (64),
	QUARTOARBITRO VARCHAR2 (64),
	CONSTRAINT PK_JOGO PRIMARY KEY (NUMERO),
	CONSTRAINT FK_JOGO_0 FOREIGN KEY (TIME1)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_JOGO_1 FOREIGN KEY (TIME2)
		REFERENCES TIME (PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_JOGO_2 FOREIGN KEY (ESTADIO)
		REFERENCES ESTADIO (NOME)
		ON DELETE CASCADE,
	CONSTRAINT CK_JOGO_0 CHECK (NUMERO >= 0),
	CONSTRAINT CK_JOGO_1 CHECK (TIME1 <> TIME2),
	CONSTRAINT CK_JOGO_2 CHECK (NGOLS1 >= 0),
	CONSTRAINT CK_JOGO_3 CHECK (NGOLS2 >= 0),
	CONSTRAINT CK_JOGO_4 CHECK (ARBITRO <> ASSISTENTE1),
	CONSTRAINT CK_JOGO_5 CHECK (ARBITRO <> ASSISTENTE2),
	CONSTRAINT CK_JOGO_6 CHECK (ARBITRO <> QUARTOARBITRO),
	CONSTRAINT CK_JOGO_7 CHECK (ASSISTENTE1 <> ASSISTENTE2),
	CONSTRAINT CK_JOGO_8 CHECK (ASSISTENTE1 <> QUARTOARBITRO),
	CONSTRAINT CK_JOGO_9 CHECK (ASSISTENTE2 <> QUARTOARBITRO)
);

CREATE TABLE PARTICIPA (
	JOGADOR NUMBER (6, 0) NOT NULL,
	NUMERO NUMBER (6, 0) NOT NULL,
	HORAENTRADA NUMBER (3, 0),
	HORASAIDA NUMBER (3, 0),
	NCARTAOAM NUMBER (1, 0) DEFAULT 0 NOT NULL,
	NCARTAOVERM NUMBER (1, 0) DEFAULT 0 NOT NULL,
	NFALTAS NUMBER (3, 0) DEFAULT 0 NOT NULL,
	NPENALTES NUMBER (3, 0) DEFAULT 0 NOT NULL,
	NGOLS NUMBER (3, 0) DEFAULT 0 NOT NULL,
	ESCALACAO CHAR (7) NOT NULL,
	CONSTRAINT PK_PARTICIPA PRIMARY KEY (JOGADOR, NUMERO),
	CONSTRAINT FK_PARTICIPA_0 FOREIGN KEY (JOGADOR)
		REFERENCES JOGADOR (NFIFA)
		ON DELETE CASCADE,
	CONSTRAINT FK_PARTICIPA_1 FOREIGN KEY (NUMERO)
		REFERENCES JOGO (NUMERO)
		ON DELETE CASCADE,
	CONSTRAINT CK_PARTICIPA_0 CHECK (HORAENTRADA >= 0 AND HORAENTRADA <= 120), -- >90 se prorrogacoes
	CONSTRAINT CK_PARTICIPA_1 CHECK (HORASAIDA >= 0 AND HORASAIDA <= 120), -- >90 se prorrogacoes
	CONSTRAINT CK_PARTICIPA_2 CHECK (HORASAIDA >= HORAENTRADA),
	CONSTRAINT CK_PARTICIPA_3 CHECK (NCARTAOAM >= 0),
	CONSTRAINT CK_PARTICIPA_4 CHECK (NCARTAOVERM >= 0),
	CONSTRAINT CK_PARTICIPA_5 CHECK (NFALTAS >= 0),
	CONSTRAINT CK_PARTICIPA_6 CHECK (NPENALTES >= 0),
	CONSTRAINT CK_PARTICIPA_7 CHECK (NGOLS >= 0),
	CONSTRAINT CK_PARTICIPA_8 CHECK (ESCALACAO IN ('TITULAR', 'RESERVA'))
);

CREATE TABLE TRABALHA (
	EQUIPE VARCHAR2 (64) NOT NULL,
	NUMERO NUMBER (6, 0) NOT NULL,
	PROCSEG VARCHAR2 (64),
	CONSTRAINT PK_TRABALHA PRIMARY KEY (EQUIPE, NUMERO),
	CONSTRAINT FK_TRABALHA_0 FOREIGN KEY (EQUIPE)
		REFERENCES EQUIPE (NOME)
		ON DELETE CASCADE,
	CONSTRAINT FK_TRABALHA_1 FOREIGN KEY (NUMERO)
		REFERENCES JOGO (NUMERO)
		ON DELETE CASCADE
);

CREATE TABLE OCORRENCIATRABALHA (
	EQUIPE VARCHAR2 (64) NOT NULL,
	NUMERO NUMBER (6, 0) NOT NULL,
	NOCORRENCIA NUMBER (6, 0) NOT NULL,
	DESCRICAO VARCHAR2 (256),
	CONSTRAINT PK_OCORRENCIATRABALHA PRIMARY KEY (EQUIPE, NUMERO, NOCORRENCIA),
	CONSTRAINT FK_OCORRENCIATRABALHA_0 FOREIGN KEY (EQUIPE, NUMERO)
		REFERENCES TRABALHA (EQUIPE, NUMERO)
		ON DELETE CASCADE
);

CREATE TABLE EMISSORA (
	NOME VARCHAR2 (64) NOT NULL,
	PAIS VARCHAR2 (64) NOT NULL,
	CONSTRAINT PK_EMISSORA PRIMARY KEY (NOME, PAIS)
);

CREATE TABLE TRANSMITE (
	NUMERO NUMBER (6, 0) NOT NULL,
	NOMEEMISSORA VARCHAR2 (64) NOT NULL,
	PAISEMISSORA VARCHAR2 (64) NOT NULL,
	TV CHAR (1) DEFAULT 'N' NOT NULL,
	RADIO CHAR (1) DEFAULT 'N' NOT NULL,
	INTERNET CHAR (1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TRANSMITE PRIMARY KEY (NUMERO, NOMEEMISSORA, PAISEMISSORA),
	CONSTRAINT FK_TRANSMITE_0 FOREIGN KEY (NUMERO)
		REFERENCES JOGO (NUMERO)
		ON DELETE CASCADE,
	CONSTRAINT FK_TRANSMITE_1 FOREIGN KEY (NOMEEMISSORA, PAISEMISSORA)
		REFERENCES EMISSORA (NOME, PAIS)
		ON DELETE CASCADE,
	CONSTRAINT CK_TRANSMITE_0 CHECK (TV IN ('S', 'N')),
	CONSTRAINT CK_TRANSMITE_1 CHECK (RADIO IN ('S', 'N')),
	CONSTRAINT CK_TRANSMITE_2 CHECK (INTERNET IN ('S', 'N'))
);

CREATE TABLE PAISTRANSM (
	NOMEEMISSORA VARCHAR2 (64) NOT NULL,
	PAISEMISSORA VARCHAR2 (64) NOT NULL,
	PAISTRANSM VARCHAR2 (64) NOT NULL,
	CONSTRAINT PK_PAISTRANSM PRIMARY KEY (NOMEEMISSORA, PAISEMISSORA, PAISTRANSM),
	CONSTRAINT FK_PAISTRANSM_0 FOREIGN KEY (NOMEEMISSORA, PAISEMISSORA)
		REFERENCES EMISSORA (NOME, PAIS)
		ON DELETE CASCADE
);

CREATE TABLE PROFISSIONAL (
	NFIFA NUMBER (6, 0) NOT NULL,
	NOME VARCHAR2 (64) NOT NULL,
	PROFISSAO VARCHAR2 (64),
	CONSTRAINT PK_PROFISSIONAL PRIMARY KEY (NFIFA)
);

CREATE TABLE EMPREGA (
	NOMEEMISSORA VARCHAR2 (64) NOT NULL,
	PAISEMISSORA VARCHAR2 (64) NOT NULL,
	NFIFAPROFISSIONAL NUMBER (6, 0) NOT NULL,
	CONSTRAINT PK_EMPREGA PRIMARY KEY (NOMEEMISSORA, PAISEMISSORA, NFIFAPROFISSIONAL),
	CONSTRAINT FK_EMPREGA_0 FOREIGN KEY (NOMEEMISSORA, PAISEMISSORA)
		REFERENCES EMISSORA (NOME, PAIS)
		ON DELETE CASCADE,
	CONSTRAINT FK_EMPREGA_1 FOREIGN KEY (NFIFAPROFISSIONAL)
		REFERENCES PROFISSIONAL (NFIFA)
		ON DELETE CASCADE
);

CREATE TABLE ACESSO (
	NFIFAPROFISSIONAL NUMBER (6, 0) NOT NULL,
	ACESSO VARCHAR2 (16) NOT NULL,
	CONSTRAINT PK_ACESSO PRIMARY KEY (NFIFAPROFISSIONAL, ACESSO),
	CONSTRAINT FK_ACESSO_0 FOREIGN KEY (NFIFAPROFISSIONAL)
		REFERENCES PROFISSIONAL (NFIFA)
		ON DELETE CASCADE
);


-- Exercício 2:

/*
2a)
Será adicionado o atributo de tamanho do campo (m X m), que pode variar entre estádios e deve estar dentro dos padrões da FIFA.

Obs.: Uma alternativa melhor para esta abordagem seria a criação de duas colunas numéricas, de largura e comprimento do campo (em metros). No entanto, decidimos usar esta abordagem para restringir a alteração a apenas uma coluna, como na especificação da prática.
*/

INSERT INTO ESTADIO VALUES ('Lusail Iconic Stadium', 'Lusail', 89000);
INSERT INTO ESTADIO VALUES ('Al Bayt Stadium', 'Al Khor', 60000);
INSERT INTO ESTADIO VALUES ('Ahmed bin Ali Stadium', 'Al Rayyan', 21282);
INSERT INTO ESTADIO VALUES ('Al Wakrah Stadium', 'Al Wakrah', 40000);
INSERT INTO ESTADIO VALUES ('Education City Stadium', 'Doha', 45350);
INSERT INTO ESTADIO VALUES ('Khalifa International Stadium', 'Doha', 40000);
INSERT INTO ESTADIO VALUES ('Ras Abu Aboud Stadium', 'Doha', 40000);
INSERT INTO ESTADIO VALUES ('Al Thumama Stadium', 'Doha', 40000);
COMMIT;

ALTER TABLE ESTADIO ADD (
	TAMANHOCAMPO CHAR (7)
	DEFAULT '075X110' -- default maximum dimensions
	NOT NULL
	CONSTRAINT CK_ESTADIO_1 CHECK (REGEXP_LIKE(TAMANHOCAMPO, '\d{3}X\d{3}', 'c')) -- checando formato da string
);

/*
Com a adição da nova coluna, todas as tuplas existentes receberam em seu novo atributo o valor padrão ('075X110'), em conformidade com as restrições impostas.
*/

/*
2b)

Para limitar os valores do atributo adicionado anteriormente, de forma que estes condizam com os padrões da FIFA, serão criadas novas restrições.
*/

ALTER TABLE ESTADIO ADD
	CONSTRAINT CK_ESTADIO_2 CHECK (TO_NUMBER(SUBSTR(TAMANHOCAMPO, 0, 3)) BETWEEN 64 AND 75);
ALTER TABLE ESTADIO ADD
	CONSTRAINT CK_ESTADIO_3 CHECK (TO_NUMBER(SUBSTR(TAMANHOCAMPO, -3)) BETWEEN 100 AND 110);

/*
2c)

Tentaremos remover a PK da tabela "Estadio" e ver as alterações nas tabelas "Jogo", "Dista" e "Treina".
*/

-- sem 'CASCADE CONSTRAINTS'
ALTER TABLE ESTADIO DROP COLUMN NOME;

-- com 'CASCADE CONSTRAINTS*'
ALTER TABLE ESTADIO DROP COLUMN NOME CASCADE CONSTRAINTS;

DESCRIBE ESTADIO;
DESCRIBE JOGO;
DESCRIBE DISTA;
DESCRIBE TREINA;

/*
Não foi possível remover a coluna sem a cláusula "CASCADE CONSTRAINTS", pois existem outras restrições referenciando este atributo. O seguinte erro foi reportado:

ORA-12992: não é possível eliminar uma coluna-chave mãe
12992. 00000 -  "cannot drop parent key column"
*Cause:    An attempt was made to drop a parent key column.
*Action:   Drop all constraints referencing the parent key column, or
			 specify CASCADE CONSTRAINTS in statement.

Com o "CASCADE CONSTRAINTS", o atributo chave "NOME" foi removido, assim como a constraint "PRIMARY KEY" da tabela. Nas demais tabelas, as constraints "FOREIGN KEY" que referenciavam a chave de "Estadio" foram todas removidas.
*/


/*
2d)

Iremos desativar a restrição "CK_ESTADIO_0", que limita o atributo "CAPACIDADE" para valores positivos.
*/
DESCRIBE ESTADIO;
ALTER TABLE ESTADIO DISABLE CONSTRAINT CK_ESTADIO_0;
INSERT INTO ESTADIO VALUES ('Buenos Aires', -100000, DEFAULT);
ALTER TABLE ESTADIO ENABLE CONSTRAINT CK_ESTADIO_0;

/*
Após a inserção da tupla inválida, não foi possível reativar a restrição "CK_ESTADIO_0", pois existe uma violação nas tuplas existentes. Para reativar, todos os valores devem estar em conformes com a restrição, como descrito no seguinte erro:

ORA-02293: não é possível validar (A9778985.CK_ESTADIO_0) - restrição de verificação violada
02293. 00000 - "cannot validate (%s.%s) - check constraint violated"
*Cause:    an alter table operation tried to validate a check constraint to
					 populated table that had nocomplying values.
*Action:   Obvious
*/
